# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'GitAction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitAction
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Kingfisher', '~> 6.0'
  pod 'SwiftGen', '~> 6.0'

  target 'GitActionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
