# This is a basic workflow to help you get started with Actions
name: Swift

on:
  push:
    branches: [ feature/*, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=GitAction/
        xcodebuild test -workspace './GitAction/GitAction.xcworkspace' -scheme 'GitActionTests' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
